services:
  backend:
    build:
      context: ./backend
    container_name: docs-analyzer-backend
    ports:
      - "8000:8000"
    volumes:
      - ./.local_data/backend:/app/data

  frontend:
    build:
      context: ./frontend
    container_name: docs-analyzer-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
